config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages, except: [:show] do
    member do
      post :edit
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  validates :body, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_message, only: %i(show edit update destroy)

  # GET /messages or /messages.json
  def index
    @pagy, @messages = pagy(Message.where("body like ?", "%#{params[:body]}%").order(id: :desc))
    @messages = @messages.reverse
  end

  # GET /messages/1 or /messages/1.json

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    # return root_path if turbo_frame_request?
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(@message, partial: "messages/form",
locals: {message: @message})
      end
    end
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        flash[:notice] = "Messages #{@message.id} is created"
        format.turbo_stream do
          render turbo_stream: handle_create_success
        end
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("new_message", partial: "messages/form", locals: {message: @message})
          ]
        end
      end
    end
  end

  def handle_create_success
    [turbo_stream.append("messages", partial: "messages/message",
                         locals: {message: @message}),
     turbo_stream.update("new_message", partial: "messages/form",
                         locals: {message: Message.new}),
     turbo_stream.update("messages_counter", Message.count)]
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.turbo_stream do
          render turbo_stream: [turbo_stream.update(@message, partial: "messages/message", locals: {message: @message}),
                                turbo_stream.update("notice",
                                                    "Messages #{@message.id} is successfully updated.")]
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(@message, partial: "messages/form",
locals: {message: @message})
        end
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.remove(@message),
                              turbo_stream.update("messages_counter", Message.count),
                              turbo_stream.update("notice", "Messages #{@message.id} was successfully destroyed.")]
      end
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_flash.html.erb
<div data-controller="autohide">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, id: key %>
  <% end %>
</div>

app/views/layouts/_sidemenu.html.erb
<div class="side-menu">
  <div class="auto-cols-auto justify-items-center">
  <div class="p-5"><i class="fa-solid fa-magnifying-glass"></i></div>
  <div class="p-5"><i class="fa-brands fa-facebook"></i></div>
  <div class="p-5"><i class="fa-brands fa-twitter"></i></div>
  <div class="p-5"><i class="fa-solid fa-phone"></i></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-bg-them="light" class="overflow-hidden">

        <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, class: "contents")  do |form| %>
    <div class="inline-flex w-full">
        <div class="body-messages">
          <%= form.text_field :body, class: "text-messages form-control-lg", placeholder: "Enter Message..." %>
        </div>
        <div class="button-message">
          <%= form.button '<i class="fa-solid fa-angles-right"></i>'.html_safe, class: "cursor-pointer" %>
        </div>
    </div>
<% end %>

app/views/messages/_message.html.erb
<div data-controller="scroll" id="<%= dom_id message %>" class="flex">
  <div class="my-3"><%= message.body %> </div>
<!--  <div class="px-5">-->
    <%#= button_to '<i class="fa-solid fa-check"></i>'.html_safe, edit_message_path(message), method: :post, class: "cursor-pointer" %>
    <%#= button_to '<i class="fa-solid fa-check"></i>'.html_safe, message_path(message), method: :delete, class: "cursor-pointer" %>
<!--  </div>-->
</div>

app/views/messages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<div id="root">
  <div class="layout-wrapper flex" data-controller= "messages" data-messages-open-value="false">
  <%= render partial:'layouts/sidemenu' %>
  <div class="chat-leftsidebar">
    <div class="text-red-500"> TOTAL MESSAGES:
      <span id="messages_counter"><%= Message.count%></span>
      <div class="px-3">

      </div>
    </div>
  </div>
  <div class="user-chat w-full">
    <div class="flex">
      <div class="w-full overflow-hidden relative">
        <div class="p-3 border-b user-chat-topbar">
          <div class="grid grid-cols-3">
            <div class="justify-start">
              <div class="p-3">
            <span> HELLO MN
              <i class="fa-solid fa-check"></i>
            </span>
              </div>
            </div>
            <div class="flex col-span-2 justify-end">
              <div class="w-full">
                <%= form_with url: messages_path, method: :get, html: {
                  data: {turbo_frame: :search_messages, messages_target: "form",}
                }  do |form|%>
                  <%= form.search_field :body, data:{ action: "input->messages#search", messages_target: "inputContent"}, class: "w-full"%>
                <% end %>
              </div>
              <button class="p-3" data-action="click->messages#openSearchInput" data-messages-target="openSearchInputContent" ><i class="fa-solid fa-magnifying-glass"></i></button>
              <button class="p-3" data-action="click->messages#closeSearchInput" data-messages-target="closeSearchInputContent" ><i class="fa-solid fa-magnifying-glass"></i></button>
              <button class="p-3"><i class="fa-brands fa-facebook"></i></button>
              <button class="p-3"><i class="fa-brands fa-twitter"></i></button>
              <button class="p-3"><i class="fa-solid fa-phone"></i></button>
            </div>
          </div>
        </div>
        <div class="px-3 chat-message">
          <%= turbo_frame_tag :search_messages do %>
              <div class="text-center" id="load-more">
                <%= link_to "Load More", pagy_url_for(@pagy, @pagy.next), method: :get, data:{turbo_stream: true} if @pagy.next %>
              </div>
            <div id="messages" class="min-w-full snap-center">
              <%= render @messages %>
            </div>
          <% end %>
            <div id="bottom"></div>
        </div>
        <div id="new_message" class="p-3 border-t user-chat-message">
          <%= render "form", message: Message.new %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/messages/index.turbo_stream.erb
<%= turbo_stream.prepend "messages" do %>
  <%=render @messages %>
<% end %>
<%= turbo_stream.update "load-more" do %>
  <%= link_to "Load More", pagy_url_for(@pagy, @pagy.next), method: :get, data:{turbo_stream: true} if @pagy.next%>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="mx-auto md:w-2/3 w-full pb-2">
    <%= render "form", message: @message %>
  </div>
<% end %>